services:
    db:
        image: mysql:8.0.45
        restart: always
        environment:
            TZ: America/Sao_Paulo
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: anir8
        ports:
            - "3308:3306"
        networks:
            - adrianoL1-network
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin" ]
            retries: 10
            interval: 3s
            timeout: 30s
    anir8:
        image: adrianol1/anir8
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            TZ: America/Sao_Paulo
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/anir8?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: admin
        ports:
            - "80:8080"
        depends_on:
            db:
                condition: service_healthy
        networks:
            - adrianoL1-network
networks:
    adrianoL1-network:
        driver: bridge
