services:
    db:
        image: mysql:9.2.0
        restart: always
        environment:
            TZ: America/Sao_Paulo
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_USER: docker
            MYSQL_PASSWORD: admin
            MYSQL_DATABASE: anir8
        ports:
            - "3308:3306"
        networks:
            - adrianoL1-network
    anir8:
        image: adrianol1/anir8
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            TZ: America/Sao_Paulo
            SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/anir8?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
            SPRING.DATASOURCE.USERNAME: root
            SPRING.DATASOURCE.PASSWORD: admin
        command: mvn spring-boot:run
        ports:
            - "80:80"
        depends_on:
            - db
        networks:
            - adrianoL1-network
networks:
    adrianoL1-network:
        driver: bridge